spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  banner:
    image:
      location: classpath:/assets/isOk.jpeg
server:
  error:
    whitelabel:
      enabled: false